### ISSUE TITLE
Button mapping upper and lower button row 

### ISSUE THREAD

**Issue by arcadeforge** [Texacate/Visual-RetroPie-Control-Maps#2]
Hey, great work. Awesome work and thanks for the efforts.

I have played around with some games kike gng, gberet, 1942.

Yxl
Bar

On all games buttons are on the lower row, means b = fire 1, a = jumom/fire 2

Is this intended by you?

For sfa3 (Street fighter) button mapping is

Kicks in the upper row
Punch in the lower row.

This should be vice versa. From what I understand you got the mappings from dat files?

Especially the default Mame2003 plus mapping for sfa3 looks completely different at my side and is mixed.

Just let you know my short tests. Perhaps they are helpful for you. At least to let you know that your work is highly appreciated.

Cheers

**Comment by Texacate** [comment]
Thank you for the feedback!   

Yes the data in primary_map.csv is directly from controls.dat v1.4.1.  The only difference is less whitespace and I removed redundant wording.  Example  "Button A" became  just "A".   The 3 databases (*_map.csv files) should all be in MAME order.

This is how my system is setup:
```
MAME   RetroPad  CntrPnl
456  -->  YXL -->  123
123  -->  BAR -->  456
```
I wanted the lower row to get used first, so I don't have to reach over used keys in most games.  So yes, that part was intentional.  

It sounds like yours is setup like this:
```
MAME   RetroPad  CntrPnl
123  -->  YXL -->  123
456  -->  BAR -->  456
```
Is that more common?  I really don't know how most folks setup their mapping in RetroPie.   I guess the default mapping should be the same as whatever RetroPie's out-of-the-box mapping is for lr-mame-2003 plus.  

Pull  the latest  `button_map.sh `  file, and let me know if it now behaves the way you expect.  I changed `function map_buttons_retro_pad () `  so the the YXL row get filled out before the BAR row.  This should flip the two rows of labels.

sfa3 now gets drawn as:
```
JabP    StrongP  FierceP
ShortK  StrongK  RndHsK
```
Better?

**Comment by arcadeforge** [comment]
Thanks a lot. This is cool.

For the wiring most cabs have a Jamma wiring. So the proposed mapping cover all cabs that have 3 buttons or neogeo 4 buttons only. Otherwise a button cab has b4, b5, b6 on the control panel.

I set in retroarch the input device type to 6 buttons using Mame2003plus. Works :)

**Comment by Texacate** [comment]
Okay.  If you have no objections, I'll close this issue.

**Comment by arcadeforge** [comment]
Sure, thanks 
--

**Comment by Texacate** [comment]
Closed.  Thank you again for the feedback!  Much appreciated.
